import * as realApi from './apiService';

// This file acts as the single entry point for all API service functions.
// It re-exports all functions from the real API service, abstracting away the
// implementation details from the rest of the application.
export const {
    login,
    getSubjects,
    getFaculty,
    getRooms,
    getDepartments,
    getBatches,
    getUsers,
    getTimetables,
    getConstraints,
    getFacultyAllocations,
    getSettings,
    runScheduler,
    runDiagnostics,
    applyNLC,
    compareTimetables,
    getAnalyticsReport,
    saveTimetable,
    updateTimetable,
    deleteTimetable,
    saveTimetableFeedback,
    saveSubject,
    deleteSubject,
    saveFaculty,
    deleteFaculty,
    saveRoom,
    deleteRoom,
    saveBatch,
    deleteBatch,
    saveDepartment,
    deleteDepartment,
    saveUser,
    deleteUser,
    savePinnedAssignment,
    deletePinnedAssignment,
    savePlannedLeave,
    deletePlannedLeave,
    saveFacultyAvailability,
    findSubstitutes,
    createSubstitution,
    saveGlobalConstraints,
    saveTimetableSettings,
    resetData,
    importDataManagementData,
} = realApi;